
import java.io.File;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author murilo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    private String path = "";
    private String path_saida = "";
    private String textoFinal ="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelSaida = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Status_arquivo = new javax.swing.JLabel();
        Status_Saida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        painelEntrada = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuLexico = new javax.swing.JMenuItem();
        MenuSintatico = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSaida.setEditable(false);
        jScrollPane1.setViewportView(painelSaida);

        jLabel1.setText("Entrada");

        jLabel2.setText("Saída");

        jScrollPane2.setViewportView(painelEntrada);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)
                        .addGap(437, 437, 437)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Status_arquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Status_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MenuLexico.setText("Abrir arquivo Lexico");
        MenuLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLexicoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLexico);

        MenuSintatico.setText("Abrir arquivo Sintatico");
        MenuSintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSintaticoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSintatico);

        menuSalvar.setText("Salvar arquivo");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Metodo executado quando o item "abrir arquivo" do menu for acionado.
     * Executa JFileChooser e ler o arquivo selecionado e mostra no painel. 
     * @param evt 
     */
    private void MenuLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLexicoActionPerformed
         /* pegar o caminho do arquivo para leitura*/
        
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //filtro apenas para arquivos txt
        file.addChoosableFileFilter(new FileNameExtensionFilter( "Arquivo texto (*.txt)", "txt"));  
        file.setAcceptAllFileFilterUsed(false);  
        // Impede seleções múltiplas.  
        file.setMultiSelectionEnabled(false);  
          int i= file.showSaveDialog(null);
       
        if (i==1){
           this.path="erro ao abrir arquivo";
           this.Status_arquivo.setText(path);
        } else {
            File arquivo = file.getSelectedFile();
            this.path=arquivo.getPath();
            System.out.println(arquivo.getPath());
            this.Status_arquivo.setText("Arquivo: "+path);
            
            //chamada do método de leitura de arquivo
            Arquivo arq = new Arquivo();
            arq.read(path);
            LinkedList<String> linha =  new LinkedList<>();
            linha = arq.getLinhas(); //pega as linhas do arquivo lido
            String text="";
            int k = 0;
            for (String linha1 : linha) {
                k++;
                if(linha1!=null){// a ultima posição na lista é null 
                    text= text+k+" "+linha1+"\n";
                }    
            }
            this.painelEntrada.setText(text); //add o texto ao painel
            
            AnalizadorLexico analizador = new AnalizadorLexico();
            LinkedList<String> Tokens = new LinkedList<String>();
            Tokens =   analizador.separarTokens(arq.getLinhas());//tokens separado, mas sem o tratamento.
            textoFinal = analizador.getTexto();//pega o texto com todos os tokens já processados
            
                                   
             this.painelSaida.setText(textoFinal); //add o texto ao painel
            
        }
        
        
    }//GEN-LAST:event_MenuLexicoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
    }//GEN-LAST:event_jMenu1ActionPerformed
    /**
     * Metodo executado quando o item "Salvar arquivo" do menu for acionado.
     * Executa JFileChooser pega o path da pasta selecionada e cria um arquivo Saida.txt. 
     * @param evt 
     */
    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //filtro apenas para arquivos txt
        //file.addChoosableFileFilter(new FileNameExtensionFilter( "Arquivo texto (*.txt)", "txt"));  
        file.setAcceptAllFileFilterUsed(false);  
        // Impede seleções múltiplas.  
        file.setMultiSelectionEnabled(false);  
          int i= file.showSaveDialog(null);
       
        if (i==1){
           this.path_saida="Erro diretorio inválido";
           this.Status_Saida.setText(path_saida);
        } else {
            File arquivo = file.getSelectedFile();
            this.path_saida=arquivo.getPath();
            //System.out.println(arquivo.getPath());
            this.Status_Saida.setText("Arquivo salvo em: "+path_saida+"\\Saida.txt");
            
            Arquivo arq = new Arquivo();
            String t = textoFinal.replaceAll("%", "%%"); //no metodo de salvar arquivo o % é um caracter de escape e precisa ter %% pra ler como %
            String fim = t.replaceAll("\n", "%n"); //quebra de linha no metodo de salvar arquivo é %n
            arq.writer(fim, this.path_saida);
            
            
           
        }
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void MenuSintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSintaticoActionPerformed
           /* pegar o caminho do arquivo para leitura*/
        
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //filtro apenas para arquivos txt
        file.addChoosableFileFilter(new FileNameExtensionFilter( "Arquivo texto (*.txt)", "txt"));  
        file.setAcceptAllFileFilterUsed(false);  
        // Impede seleções múltiplas.  
        file.setMultiSelectionEnabled(false);  
          int i= file.showSaveDialog(null);
       
        if (i==1){
           this.path="erro ao abrir arquivo";
           this.Status_arquivo.setText(path);
        } else {
            File arquivo = file.getSelectedFile();
            this.path=arquivo.getPath();
            System.out.println(arquivo.getPath());
            this.Status_arquivo.setText("Arquivo: "+path);
            
            //chamada do método de leitura de arquivo
            Arquivo arq = new Arquivo();
            arq.read(path);
            LinkedList<String> linha =  new LinkedList<>();
            linha = arq.getLinhas(); //pega as linhas do arquivo lido
            String text="";
            int k = 0;
            for (String linha1 : linha) {
                k++;
                if(linha1!=null){// a ultima posição na lista é null 
                    text= text+k+" "+linha1+"\n";
                }    
            }
            this.painelEntrada.setText(text); //add o texto ao painel
             //chamar o analisador sintatico aqui
            AnalizadorSintatico sintatico = new AnalizadorSintatico();
            AnalizadorLexico lexico = new AnalizadorLexico();
            lexico.separarTokens(arq.getLinhas());//tokens separado, mas sem o tratamento.
            
            List<String> ListTokens = lexico.getTokens();
            
            sintatico.IniciarSintatico(ListTokens);
            
            textoFinal = "Saída do léxico:\n"+lexico.getTexto();
            textoFinal = textoFinal+"\n\nSaída do sintático:\n"+sintatico.getErros()+"\n\n";
            
            if(!lexico.getErro()&&!sintatico.getErro()){
                textoFinal=textoFinal+"Sucesso!: nenhum erro encontrado!";
            }else if(lexico.getErro()&&sintatico.getErro()){
                textoFinal=textoFinal+"Há erro(s) léxico(s) e sintático(s)";
              
            }else if(sintatico.getErro()){
                 textoFinal=textoFinal+"Há erro(s) sintático(s)";
            }else if(lexico.getErro()){
                  textoFinal=textoFinal+"Há erro(s) léxico(s)";
            }
            
            this.painelSaida.setText(textoFinal); //add o texto ao painel
            
        }
    }//GEN-LAST:event_MenuSintaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuLexico;
    private javax.swing.JMenuItem MenuSintatico;
    private javax.swing.JLabel Status_Saida;
    private javax.swing.JLabel Status_arquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JTextPane painelEntrada;
    private javax.swing.JTextPane painelSaida;
    // End of variables declaration//GEN-END:variables
}
